ALTER TABLE account ADD COLUMN deleted BOOLEAN;
ALTER TABLE account ALTER COLUMN deleted SET DEFAULT false;

ALTER TABLE category ADD COLUMN deleted BOOLEAN;
ALTER TABLE category ALTER COLUMN deleted SET DEFAULT false;

ALTER TABLE color ADD COLUMN deleted BOOLEAN;
ALTER TABLE color ALTER COLUMN deleted SET DEFAULT false;

ALTER TABLE image ADD COLUMN deleted BOOLEAN;
ALTER TABLE image ALTER COLUMN deleted SET DEFAULT false;

ALTER TABLE memory ADD COLUMN deleted BOOLEAN;
ALTER TABLE memory ALTER COLUMN deleted SET DEFAULT false;

ALTER TABLE model ADD COLUMN deleted BOOLEAN;
ALTER TABLE model ALTER COLUMN deleted SET DEFAULT false;

ALTER TABLE product ADD COLUMN deleted BOOLEAN;
ALTER TABLE product ALTER COLUMN deleted SET DEFAULT false;
